#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH" PATH="$HERE/usr/bin:$PATH" SPACEVIMDIR="$HERE"/SpaceVim.d/ ${HERE}/usr/bin/nvim -u $HERE/SpaceVim/vimrc

