[options]
    colorscheme = "onedark"
    automatic_update = true
    enable_guicolors = true 
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    vimcompatible = true
    filemanager = "nerdtree"
    filetree_direction = "left"
    snippet_engine = "ultisnips"
    bootstrap_after = 'myspacevim#after'
    windows_leader = "s"

[[custom_plugins]]
  repo = 'mjbrownie/django_completeme'

[[custom_plugins]]
  repo = 'unblevable/quick-scope'

[[custom_plugins]]
  repo = 'tweekmonster/django-plus.vim'

[[custom_plugins]]
  repo = 'sukima/xmledit'

[[custom_plugins]]
  repo = 'jmcomets/vim-pony'

[[custom_plugins]]
  repo = 'yuratomo/w3m.vim'

[[custom_plugins]]
  repo = 'hienvd/vim-stackoverflow'

[[custom_plugins]]
  repo = 'rafi/awesome-vim-colorschemes'

[[custom_plugins]]
  repo = 'kdheepak/lazygit.nvim'
  branch = 'nvim-v0.4.3'

[[layers]]
    name = "incsearch"

[[layers]]
  name = "checkers"
  lint_on_save = true

[[layers]]
  name = "debug"

[[layers]]
  name = "lang#html"
  format_on_save = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  clang_flag = ['-I/user/include']
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "format"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "python",
    "sh",
    "cpp",
    "css",
    "javascript"
  ]
  [layers.override_cmd]
    rust = ["rls"]

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "sudo"

[[layers]]
    name = "foldsearch"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#vim"

[[layers]]
    name = "tools"

[[layers]]
  name = "leaderf"

[[layers]]
  name = "github"

[[layers]]
  name = "fzf"

[[layers]]
  name = "lang#python"
  format_on_save = true
