[options]
    colorscheme = "onedark"
    enable_guicolors = true 
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    vimcompatible = true
    filemanager = "nerdtree"
    filetree_direction = "left"
    snippet_engine = "ultisnips"
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

[[custom_plugins]]
  repo = 'sukima/xmledit'
  merge=0 

[[custom_plugins]]
  repo = 'jmcomets/vim-pony'
  merge=0 

[[custom_plugins]]
  repo = 'rafi/awesome-vim-colorschemes'
  merge=0 

[[custom_plugins]]
  repo = 'kdheepak/lazygit.nvim'
  merge=0 

[[layers]]
  name = "checkers"
  lint_on_save = true

[[layers]]
  name = "debug"

[[layers]]
  name = "lang#html"
  format_on_save = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  clang_flag = ['-I/user/include']
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "format"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "git"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#python"
  format_on_save = true
