name: SpaceVim appimage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget nodejs npm python3 python3-pip
      - name: Build AppImage
        run: |
          ./build_appimage.sh
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
      - uses: ncipollo/release-action@v1
        env: 
          SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          name: nvim.AppImage
          artifacts: nvim.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: True
          tag: ${{ env.SHA }}


