name: SpaceVim appimage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget nodejs npm python3 python3-pip
      - name: Build AppImage
        run: |
          ./build_appimage.sh
      - name: set env
        run: "export tagnow=$(git rev-parse --short HEAD)"
      - uses: ncipollo/release-action@v1
        with:
          name: nvim.AppImage
          artifacts: nvim.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: True
          tag: ${{ github.sha }}



